const friends = [
  {
    id: "user1",
    photo: require("./assets/avatar.jpg"),
    name: "user1",
    start: "",
    newMessages: 3,
  },
  {
    id: "user2",
    photo: require("./assets/avatar.jpg"),
    name: "user2",
    start: "",
    newMessages: 2,
  },
  {
    id: "user3",
    photo: require("./assets/avatar.jpg"),
    name: "user3",
    start: "",
    newMessages: 1,
  },
  {
    id: "user4",
    photo: require("./assets/avatar.jpg"),
    name: "user4",
    start: "",
    newMessages: 0,
  },
  {
    id: "user5",
    photo: require("./assets/avatar.jpg"),
    name: "user5",
    start: "",
    newMessages: 0,
  },
  {
    id: "user6",
    photo: require("./assets/avatar.jpg"),
    name: "user6",
    start: "",
    newMessages: 0,
  },
  {
    id: "user7",
    photo: require("./assets/avatar.jpg"),
    name: "user7",
    start: "",
    newMessages: 0,
  },
  {
    id: "user8",
    photo: require("./assets/avatar.jpg"),
    name: "user8",
    start: "",
    newMessages: 0,
  },
  {
    id: "user9",
    photo: require("./assets/avatar.jpg"),
    name: "user9",
    start: "",
    newMessages: 0,
  },
  {
    id: "user10",
    photo: require("./assets/avatar.jpg"),
    name: "user10",
    start: "",
    newMessages: 0,
  },
  {
    id: "user11",
    photo: require("./assets/avatar.jpg"),
    name: "user11",
    start: "",
    newMessages: 0,
  },
  {
    id: "user12",
    photo: require("./assets/avatar.jpg"),
    name: "user12",
    start: "",
    newMessages: 0,
  },
  {
    id: "user13",
    photo: require("./assets/avatar.jpg"),
    name: "user13",
    start: "",
    newMessages: 0,
  },
  {
    id: "user14",
    photo: require("./assets/avatar.jpg"),
    name: "user14",
    start: "",
    newMessages: 0,
  },
  {
    id: "user15",
    photo: require("./assets/avatar.jpg"),
    name: "user15",
    start: "",
    newMessages: 0,
  },
];

export default friends;
